### ISSUE TITLE
想问一下关于用pandar40p loam建图的事情

### ISSUE THREAD

**Issue by w634307272** [HesaiTechnology/HesaiLidar_General_ROS#19]
禾赛科技的工程师：
你们好！
我使用了官网上面下载的车道线pcap文件，部署完成了ros环境配置，现在运行loam以后通过将fixedframe设置为Pandar40P，可以回放pcap文件显示点云数据，但是无法进行loam的同步建图，Global status中显示 no tf data。
想咨询一下我应该具体如何设置才能完成loam的建图，还是需要修改loam的源码。
感激不尽！期待您的回答！

**Comment by yangfanFred** [comment]
Hi w634307272,

这应该是loam的配置问题，需要你们在loam里面配置一下，loam默认监听的是velodyne的topic name

Thanks,
Fred

**Comment by w634307272** [comment]
> Hi w634307272,
> 
> 这应该是loam的配置问题，需要你们在loam里面配置一下，loam默认监听的是velodyne的topic name
> 
> Thanks,
> Fred
谢谢 问题解决了
