### ISSUE TITLE
How to connect to GPS with Pandar20B?

### ISSUE THREAD

**Issue by AaronWaxson** [HesaiTechnology/HesaiLidar_General_ROS#20]
I have a gps device but the ip addrres is different to Pandar20B, so I don't know how to connect to GPS with Pandar20B.
And after that how to use it?

**Comment by yangfanFred** [comment]
Hi Aaron,

GPS module need to be connected to Lidar through the GPS hardware interface on Lidar connection box, you can read our mannual for details. Only PTP master device can give lidar time when they are in same sub network, read our mannual for details. 

Thanks,
Fred
