### ISSUE TITLE
关于ros驱动后发出的一帧点云是否正好包含360°数据

### ISSUE THREAD

**Issue by zzy1771706** [HesaiTechnology/HesaiLidar_General_ROS#39]
您好。我们项目使用了pandar40p这款雷达。依据产品说明书。雷达在转速为600rpm时，水平分辨率0.2°。我阅读ros驱动代码，感觉代码是将10个block封装为一个package。也就是一个package代表2°的数据。但是我没有找到一帧topic为/pandar的pointcloud2，包含的数据是否正好是雷达旋转360°的数据，即正好由180个package构成。
综上，我的问题主要是pandar40p经ros驱动后，发出的话题为/pandar的一帧点云是否正好包含的是雷达旋转360°数据。或者是包含了360°以上的数据。如果您能解答我真的万分感谢。。

**Comment by yangfanFred** [comment]
您好，ros driver解析每一个package内的所有点云数据，当检测到

**Comment by zhangyu-hesaitech** [comment]
每一帧的pointcloduud2点云数为0-360度内有效点数，不等于180个package换算过来的总数，距离大于200m或小于0.1m会被过滤掉，详情请参考代码中的calcuPointXYZI函数
