### ISSUE TITLE
Support ROS2 

### ISSUE THREAD

**Issue by harderthan** [HesaiTechnology/HesaiLidar_General_ROS#40]
Hello. 

I would like to discuss the support ros2 for HesaiLidar_General_ROS. 
**Is there a plan to support ros2?** I didn't find ros2 driver for PandarQT lidar from yours.

**Comment by yangfanFred** [comment]
Hi Harderthan,

We have the plan to support ros2 and is wokring on it, will release once finished and fully tested.
Thanks for your contribute.

Thanks

**Comment by harderthan** [comment]
Hello, @yangfanFred .
Thank you for the sharing about your plan to support `ros2` . 

I developed the ROS2 driver based on [the ROS1 driver repository](https://github.com/HesaiTechnology/HesaiLidar_General_ROS) you provide, with @joonr7.
You can check the code from [here](https://github.com/joonr7/HesaiLidar_General_ROS2/tree/dashing-devel).

I hope this is useful to you. Also, let me know if this code have some problem.

**Comment by zhangyu-hesaitech** [comment]
Hello, @harderthan 
Thanks for your contribute.
I didn't find a way to use Time in ROS2 msg before，your code give a good example,it helps me a lot

**Comment by harderthan** [comment]
Thanks! @zhangyu-hesaitech , @dadaroce
