### ISSUE TITLE
Timestamp realtime source??

### ISSUE THREAD

**Issue by BaichenBadrakh** [HesaiTechnology/HesaiLidar_General_ROS#61]
I have Pandar64, using it for SLAM with Imu and other sensors. I need time synchronazition, what is timestamp realtime time source? Can i change the time source for ros::TIme::Now(), because time synchornize still has big problem for me.

**Comment by yangfanFred** [comment]
> I have Pandar64, using it for SLAM with Imu and other sensors. I need time synchronazition, what is timestamp realtime time source? Can i change the time source for ros::TIme::Now(), because time synchornize still has big problem for me.

real time means use the packate receive system time as the timestamp for points, which is not accurate.
PTP or GPS is recommaned for time synchronazition.

**Comment by BaichenBadrakh** [comment]
Thanks for reply, but there is very few information about PTP or GPS time synchronazition, can u share more information about how to do PTP or GPS for time source.

**Comment by yangfanFred** [comment]
> Thanks for reply, but there is very few information about PTP or GPS time synchronazition, can u share more information about how to do PTP or GPS for time source.

which lidar model are you using? do you have the user mannual of the lidar unit? you can contact your salesman to get a copy of the user mannual, introductions about gps and ptp were included in the nuser mannual. As for ptp master, you can search the "PTP4L" tool, which can make your PC act as a PTP master to sync time of lidar.

**Comment by BaichenBadrakh** [comment]
thanks for reply, close the issue
