### ISSUE TITLE
Error build source code

### ISSUE THREAD

**Issue by duclinhfetel** [HesaiTechnology/HesaiLidar_General_ROS#8]
## Environment:
* OS: ubuntu 20.04
* ROS version: ROS Noetic Ninjemys

## Change
* PCL on ubuntu 20.04 needs c++14 --> I changed CMakeLists.txt from c++11 to c++14
When i run catkin_make, I get notice error boost.

I want to fix this problem. Could everyone help me?
Thanks

**Comment by beltransen** [comment]
Same case here. I had to change the compiler version, but still, a _boost_ error appears. Here it is the screenshot of the error:
![image](https://user-images.githubusercontent.com/2643936/87142821-60f0af00-c2a5-11ea-95e4-308026c6d3ca.png)

**Comment by yangfanFred** [comment]
Hi duclinhfetel and beltransen,

Our prjects were mostly built and tested on Ubuntu16.04 & ROS Kinetic since this evnironment are the most common used and stable combo. We didn't offically support Ubuntu 20.04 yet, we will look into this requirement and give feedbacks very soon.

Thank you
