### ISSUE TITLE
How to grabber one frame?

### ISSUE THREAD

**Issue by diennv** [HesaiTechnology/HesaiLidar_General_ROS#9]
Hi Mr @hesaiwuxiaozhou,

We received two PandarQT from your company.

We are exploring your devices. Using your SDK, we can receive Cloud Points by lidar_callback() function.

We now want to receive a entire frame (360 degree) then analysis and display.
 
Do you support any samples for that? If no, please tell us, how to do that.

Thanks,

**Comment by yangfanFred** [comment]
Hi Diennv,

The lidar_callback() function will be called only once in one 360 degree turning cycle(1 frame).
And the ouput point clouds are all points collected in this cycle(1 frame).

Thanks
